import "dotenv/config";
import mongoose from "mongoose";
import { connectDB } from "../config/db";
import { Recipe } from "../models/Recipe";

const sampleRecipes = [
  {
    title: "Garlic Butter Chicken Skillet",
    shortDesc: "Pan-seared chicken thighs finished in a garlicky herb butter sauce.",
    steps: [
      "Season chicken thighs with salt and pepper.",
      "Sear in a hot skillet 6 minutes per side until golden.",
      "Add butter, minced garlic, and thyme; baste for 2 minutes.",
      "Rest 5 minutes before serving with pan sauce spooned over.",
    ],
    ingredients: [
      { name: "Chicken thighs", qty: "500g" },
      { name: "Garlic cloves", qty: "6" },
      { name: "Butter", qty: "3 tbsp" },
      { name: "Fresh thyme", qty: "2 sprigs" },
    ],
    images: ["https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600"],
    cuisineType: "Continental",
    dietType: "High-Protein",
    cookTime: 25,
    difficulty: "Easy",
    servings: 2,
    tags: ["quick", "weeknight", "garlicky"],
    nutrition: { calories: 420, protein: 38, carbs: 4, fat: 28 },
    ratingAvg: 4.8,
    ratingCount: 34,
  },
  {
    title: "Spinach & Egg Skillet",
    shortDesc: "A one-pan breakfast loaded with greens and soft eggs.",
    steps: [
      "Wilt spinach in olive oil with a pinch of salt.",
      "Make wells in the spinach and crack in the eggs.",
      "Cover and cook until whites set but yolks stay soft.",
      "Finish with black pepper and chili flakes.",
    ],
    ingredients: [
      { name: "Fresh spinach", qty: "200g" },
      { name: "Eggs", qty: "3" },
      { name: "Olive oil", qty: "1 tbsp" },
      { name: "Chili flakes", qty: "1 tsp" },
    ],
    images: ["https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600"],
    cuisineType: "Continental",
    dietType: "Vegetarian",
    cookTime: 15,
    difficulty: "Easy",
    servings: 1,
    tags: ["breakfast", "quick", "one-pan"],
    nutrition: { calories: 280, protein: 18, carbs: 6, fat: 20 },
    ratingAvg: 4.6,
    ratingCount: 21,
  },
  {
    title: "Tomato Basil Risotto",
    shortDesc: "Creamy arborio rice simmered with fresh tomato and basil.",
    steps: [
      "Saute onion in butter until translucent.",
      "Add arborio rice and toast for 2 minutes.",
      "Add warm stock one ladle at a time, stirring constantly.",
      "Fold in chopped tomato and basil just before serving.",
    ],
    ingredients: [
      { name: "Arborio rice", qty: "1 cup" },
      { name: "Vegetable stock", qty: "4 cups" },
      { name: "Ripe tomatoes", qty: "3" },
      { name: "Fresh basil", qty: "1 handful" },
    ],
    images: ["https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600"],
    cuisineType: "Italian",
    dietType: "Vegetarian",
    cookTime: 40,
    difficulty: "Medium",
    servings: 3,
    tags: ["comfort-food", "creamy", "date-night"],
    nutrition: { calories: 360, protein: 8, carbs: 62, fat: 9 },
    ratingAvg: 4.9,
    ratingCount: 48,
  },
  {
    title: "Ginger Soy Salmon",
    shortDesc: "Flaky salmon glazed with a ginger-soy reduction.",
    steps: [
      "Whisk soy sauce, grated ginger, and honey for the glaze.",
      "Sear salmon skin-side down until crisp, 4 minutes.",
      "Flip, add glaze, and simmer until it thickens.",
      "Serve over rice with the glaze spooned on top.",
    ],
    ingredients: [
      { name: "Salmon fillets", qty: "2" },
      { name: "Soy sauce", qty: "3 tbsp" },
      { name: "Fresh ginger", qty: "1 tbsp grated" },
      { name: "Honey", qty: "1 tbsp" },
    ],
    images: ["https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600"],
    cuisineType: "Chinese",
    dietType: "High-Protein",
    cookTime: 20,
    difficulty: "Medium",
    servings: 2,
    tags: ["seafood", "glazed", "quick"],
    nutrition: { calories: 390, protein: 34, carbs: 12, fat: 22 },
    ratingAvg: 4.7,
    ratingCount: 29,
  },
  {
    title: "Bhuna Khichuri",
    shortDesc: "Comforting Bangladeshi rice-and-lentil one-pot, rich with roasted spices.",
    steps: [
      "Dry-roast rice and moong dal together until fragrant.",
      "Saute onion, ginger-garlic paste, and whole spices in ghee.",
      "Add rice, dal, and vegetables; stir to coat in the masala.",
      "Pour in hot water and simmer covered until soft and thick.",
    ],
    ingredients: [
      { name: "Rice", qty: "1 cup" },
      { name: "Moong dal", qty: "1/2 cup" },
      { name: "Ghee", qty: "2 tbsp" },
      { name: "Mixed vegetables", qty: "1 cup" },
    ],
    images: ["https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600"],
    cuisineType: "Bangladeshi",
    dietType: "Vegetarian",
    cookTime: 35,
    difficulty: "Medium",
    servings: 4,
    tags: ["comfort-food", "rainy-day", "one-pot"],
    nutrition: { calories: 340, protein: 11, carbs: 58, fat: 8 },
    ratingAvg: 4.9,
    ratingCount: 52,
  },
  {
    title: "Chicken Tikka Masala",
    shortDesc: "Charred marinated chicken in a creamy spiced tomato gravy.",
    steps: [
      "Marinate chicken in yogurt and spices for at least 1 hour.",
      "Char the chicken under a broiler or on a hot pan.",
      "Simmer tomato, cream, and spices into a smooth gravy.",
      "Fold the charred chicken into the gravy and simmer 5 minutes.",
    ],
    ingredients: [
      { name: "Chicken breast", qty: "500g" },
      { name: "Yogurt", qty: "1/2 cup" },
      { name: "Tomato puree", qty: "1 cup" },
      { name: "Heavy cream", qty: "1/4 cup" },
    ],
    images: ["https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600"],
    cuisineType: "Indian",
    dietType: "High-Protein",
    cookTime: 45,
    difficulty: "Medium",
    servings: 4,
    tags: ["creamy", "spicy", "crowd-pleaser"],
    nutrition: { calories: 460, protein: 36, carbs: 14, fat: 29 },
    ratingAvg: 4.8,
    ratingCount: 61,
  },
  {
    title: "Margherita Flatbread",
    shortDesc: "Thin, crisp flatbread with tomato, fresh mozzarella, and basil.",
    steps: [
      "Roll dough thin and prick lightly with a fork.",
      "Spread a thin layer of tomato sauce, leaving a border.",
      "Scatter torn mozzarella evenly across the top.",
      "Bake at high heat until the crust blisters, then finish with basil.",
    ],
    ingredients: [
      { name: "Pizza dough", qty: "1 ball" },
      { name: "Tomato sauce", qty: "1/3 cup" },
      { name: "Fresh mozzarella", qty: "125g" },
      { name: "Fresh basil", qty: "handful" },
    ],
    images: ["https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600"],
    cuisineType: "Italian",
    dietType: "Vegetarian",
    cookTime: 20,
    difficulty: "Easy",
    servings: 2,
    tags: ["quick", "kid-friendly", "cheesy"],
    nutrition: { calories: 410, protein: 17, carbs: 48, fat: 16 },
    ratingAvg: 4.6,
    ratingCount: 27,
  },
  {
    title: "Kung Pao Cauliflower",
    shortDesc: "Crispy roasted cauliflower tossed in a sweet-spicy kung pao sauce.",
    steps: [
      "Roast cauliflower florets until golden and crisp-edged.",
      "Whisk soy sauce, vinegar, chili paste, and sugar for the sauce.",
      "Toss roasted cauliflower and peanuts in the sauce over heat.",
      "Garnish with scallions and serve over rice.",
    ],
    ingredients: [
      { name: "Cauliflower", qty: "1 head" },
      { name: "Soy sauce", qty: "3 tbsp" },
      { name: "Roasted peanuts", qty: "1/3 cup" },
      { name: "Chili paste", qty: "1 tbsp" },
    ],
    images: ["https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600"],
    cuisineType: "Chinese",
    dietType: "Vegan",
    cookTime: 30,
    difficulty: "Medium",
    servings: 3,
    tags: ["spicy", "vegan", "crispy"],
    nutrition: { calories: 300, protein: 10, carbs: 32, fat: 15 },
    ratingAvg: 4.5,
    ratingCount: 19,
  },
  {
    title: "Keto Zucchini Lasagna",
    shortDesc: "Layered zucchini ribbons standing in for pasta, with a rich meat sauce.",
    steps: [
      "Salt sliced zucchini and let it sit to draw out moisture.",
      "Brown ground beef with garlic and simmer in tomato sauce.",
      "Layer zucchini, meat sauce, and ricotta in a baking dish.",
      "Bake covered, then uncover to brown the cheese on top.",
    ],
    ingredients: [
      { name: "Zucchini", qty: "3 large" },
      { name: "Ground beef", qty: "400g" },
      { name: "Ricotta cheese", qty: "1 cup" },
      { name: "Mozzarella", qty: "1 cup" },
    ],
    images: ["https://images.unsplash.com/photo-1619895092538-128341789043?w=600"],
    cuisineType: "Italian",
    dietType: "Keto",
    cookTime: 55,
    difficulty: "Hard",
    servings: 4,
    tags: ["low-carb", "cheesy", "meal-prep"],
    nutrition: { calories: 480, protein: 32, carbs: 10, fat: 34 },
    ratingAvg: 4.7,
    ratingCount: 23,
  },
  {
    title: "Beef Tacos with Pickled Onion",
    shortDesc: "Spiced ground beef tacos brightened with quick-pickled red onion.",
    steps: [
      "Quick-pickle sliced red onion in vinegar, sugar, and salt.",
      "Brown ground beef with cumin, paprika, and chili powder.",
      "Warm tortillas and fill with beef, onion, and fresh cilantro.",
      "Finish with a squeeze of lime.",
    ],
    ingredients: [
      { name: "Ground beef", qty: "400g" },
      { name: "Corn tortillas", qty: "8" },
      { name: "Red onion", qty: "1" },
      { name: "Lime", qty: "1" },
    ],
    images: ["https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600"],
    cuisineType: "Continental",
    dietType: "High-Protein",
    cookTime: 25,
    difficulty: "Easy",
    servings: 4,
    tags: ["quick", "crowd-pleaser", "weeknight"],
    nutrition: { calories: 380, protein: 26, carbs: 30, fat: 17 },
    ratingAvg: 4.6,
    ratingCount: 31,
  },
  {
    title: "Vegan Buddha Bowl",
    shortDesc: "Roasted sweet potato, chickpeas, and greens with a tahini drizzle.",
    steps: [
      "Roast cubed sweet potato and chickpeas until golden.",
      "Whisk tahini, lemon juice, and water into a smooth dressing.",
      "Arrange greens, roasted vegetables, and chickpeas in a bowl.",
      "Drizzle with tahini dressing just before serving.",
    ],
    ingredients: [
      { name: "Sweet potato", qty: "2" },
      { name: "Chickpeas", qty: "1 can" },
      { name: "Mixed greens", qty: "2 cups" },
      { name: "Tahini", qty: "3 tbsp" },
    ],
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600"],
    cuisineType: "Continental",
    dietType: "Vegan",
    cookTime: 35,
    difficulty: "Easy",
    servings: 2,
    tags: ["vegan", "meal-prep", "colorful"],
    nutrition: { calories: 420, protein: 14, carbs: 56, fat: 16 },
    ratingAvg: 4.8,
    ratingCount: 40,
  },
  {
    title: "Butter Garlic Naan",
    shortDesc: "Soft, pillowy flatbread brushed with garlic butter, straight from the pan.",
    steps: [
      "Knead a soft yogurt-enriched dough and let it rest 2 hours.",
      "Divide and roll into teardrop shapes.",
      "Cook on a hot skillet until bubbled and charred in spots.",
      "Brush immediately with garlic butter and fresh coriander.",
    ],
    ingredients: [
      { name: "All-purpose flour", qty: "2 cups" },
      { name: "Yogurt", qty: "1/4 cup" },
      { name: "Butter", qty: "3 tbsp" },
      { name: "Garlic", qty: "3 cloves" },
    ],
    images: ["https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600"],
    cuisineType: "Indian",
    dietType: "Vegetarian",
    cookTime: 150,
    difficulty: "Medium",
    servings: 6,
    tags: ["bread", "garlicky", "side-dish"],
    nutrition: { calories: 220, protein: 6, carbs: 34, fat: 7 },
    ratingAvg: 4.7,
    ratingCount: 18,
  },
];

const run = async () => {
  await connectDB();

  // Find the demo user's id so seeded recipes have a valid, consistent author.
  const usersCollection = mongoose.connection.collection("user");
  const demoUser = await usersCollection.findOne({ email: "demo@mealmind.ai" });
  const authorId = demoUser?._id?.toString() || "demo-seed-author";

  await Recipe.deleteMany({ authorId });
  await Recipe.insertMany(sampleRecipes.map((r) => ({ ...r, authorId })));

  console.log(`Seeded ${sampleRecipes.length} sample recipes.`);
  await mongoose.disconnect();
  process.exit(0);
};

run().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
